[package]
name = "feanor-math-hexl"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["rlib"]
bench = true

[dependencies]
cpp = "0.5.9"
feanor-math = "1.2.0"

[build-dependencies]
cpp_build = "0.5"
